export const Companies = () => {
  return [
    "UNICONTROL CONTROLE DE PRAGAS LTDA",
    "UNICONTROL CONTROLE DE PRAGAS S/A - FILIAL FARROUPILHA",
    "FITOLOG LICENCIAMENTO DE FRANQUIAS LTDA",
    "NEWSIS SISTEMAS E SERVIÇOS DE INTERNET LTDA",
  ];
};
