export const Level = () => {
    return [
        "Agenciador de propaganda",
        "Agrônomo Júnior",
        "Agrônomo Pleno",
        "Analista Administrativo",
        "Analista de RH",
        "Analista de Vendas",
        "Assistente Administrativo",
        "Assistente de Vendas",
        "Assistente de RH",
        "Aprendiz",
        "Auxiliar Administrativo",
        "Auxiliar Administrativo Financeiro",
        "Auxiliar Administrativo/Operacional",
        "Auxiliar Contábil",
        "Auxiliar de Marketing",
        "Auxiliar de Vendas",
        "Biologa Júnior",
        "Biologa Pleno",
        "Biologa Sênior",
        "Consultor Comercial",
        "Consultor de Processos",
        "Consultor de RH",
        "Controlador de Pragas",
        "Controlador de Pragas Júnior",
        "Controlador de Pragas Master",
        "Controlador de Pragas Pleno",
        "Controlador de Pragas Sênior",
        "Diretor-Presidente",
        "Diretor",
        "Engenheiro Agrônomo",
        "Estagiário",
        "Analista de Negócios",
        "Gerente Comercial",
        "Gerente de Unidade",
        "Gerente Geral",
        "Supervisor de Vendas",
        "Supervisor Técnico",
        "Técnico de Segurança do Trabalho",
      ];
  };
  