export const Office = () => {
    return [
      "Agenciador de Propagranda",
      "Agrônomo Júnior",
      "Agrônomo Pleno",
      "Analista Administrativo",
      "Analista de DP",
      "Analista de Marketing",
      "Analista de Negócios",
      "Analista de RH",
      "Analista de Vendas",
      "Aprendiz",
      "Assistente Adiministrativo",
      "Assistente de Atendimento",
      "Assistente de DP",
      "Assistente de RH",
      "Assistente de Vendas",
      "Autonônomo",
      "Auxiliar ADM Operacional",
      "Auxiliar Administrativo",
      "Auxiliar Administrativo Financeiro",
      "Auxiliar Contábil",
      "Auxiliar de DP",
      "Auxiliar de Marketing",
      "Auxiliar de Vendas",
      "Bióloga Júnior",
      "Bióloga Pleno",
      "Bióloga Sênior",
      "Consultor de Processos",
      "Controlador de Pragas",
      "Controlador de Pragas Júnior",
      "Controlador de Pragas Master",
      "Controlador de Pragas Pleno",
      "Controlador de Pragas Sênior",
      "Desenvolvedor de TI",
      "Diretor - Presidente",
      "Engenheiro Agrônomo",
      "Estagiário",
      "Gerente Comercial",
      "Gerente Geral",
      "Gerente da Unidade",
      "Representante Comercial",
      "Supervisor Técnico",
      "Supervisor de Vendas",
      "Técnico de Segurança do Trabalho",
      "Técnico em Manutenção"
    ];
  };
  